import createActions from 'redux-actions-generator'

export default createActions('', [
  'ETHEREUM_INIT',
  'ETHEREUM_READY',
  'ETHEREUM_ERROR',
  'ETHEREUM_MISSING_METAMASK',
  'ETHEREUM_ACCOUNT_CHANGE',
  'ETHEREUM_UPDATE_BALANCE',
  'BUY_TOKEN_SET_COINS',
  'BUY_TOKEN_LOADING',
  'APP_ERROR',
  'PIXELS_UPDATED',
  'CLOSE_MODAL',
  'SET_TRANSACTION_STATUS',
  'CLEAR_PIXEL',
  'SELECT_PIXEL',
  'SET_PIXEL_COLOR',
  'SET_LEASE_TIME',
  'BUY_PIXEL_LOADING'
])
